### ISSUE TITLE
Error launching Adonis v5 app using latest cliui version

### ISSUE THREAD

**Issue by fareeda0** [poppinss/cliui#5]
## Description

Latest version on npm `2.1.0` throws `SyntaxError: Unexpected token '.'`  in `build/src/Task/index.js:45`

This can be reproduced by running `yarn create adonis-ts-app <name>`, then running `yarn dev` (or npm equivalent)

## Package version
`2.1.0`

## Error Message & Stack Trace

```
yarn run v1.22.4
$ node ace serve --watch
/Users/fareed/Test/node_modules/@poppinss/cliui/build/src/Task/index.js:45
        this.onUpdateListener?.(this);
                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/fareed/Test/node_modules/@poppinss/cliui/build/src/Task/Manager.js:12:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
error Command failed with exit code 1.
```
## Relevant Information

Worth noting that a new version was released on npm ~ 2 hours ago.

**Comment by thetutlage** [comment]
Thanks for reporting. Can you share the Node.js version you are using?

**Comment by fareeda0** [comment]
> Thanks for reporting. Can you share the Node.js version you are using?

v12.18.3

**Comment by thetutlage** [comment]
Cool. I will patch this. However, we will be moving to Node 14 around next month, since it is the new LTS for Node.js. So if upgrading version is not an issue for you, then I recommend using the LTS version

**Comment by thetutlage** [comment]
Want to give it a try now with `v2.1.1` version

**Comment by fareeda0** [comment]
Yep, just tried now and it's working.
